[project]
name = "chess-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mark Grivainis", email = "markgrivainis@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
chess-db = "chess_db:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
