[project]
name = "chess-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mark Grivainis", email = "markgrivainis@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chess>=1.11.2",
    "click>=8.5.0",
    "psycopg[binary]>=3.0",
    "pydantic>=2.13.5",
    "python-chess>=1.999",
    "requests>=2.34.2",
]

[project.scripts]
chess-db = "chess_db:cli"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
